add set -e

diff --git a/color_xterm b/color_xterm
--- a/color_xterm
+++ b/color_xterm
@@ -8,8 +8,11 @@
 #
 # ===============================================
 
+# Exit when command fail
+set -o errexit
+
 # My fun colors
-XTERM_COLORS=(
+readonly XTERM_COLORS=(
     'lightgreen'
     'lime'
     'skyblue'
@@ -18,27 +21,31 @@ XTERM_COLORS=(
 )
 
 # FG is BLACK !
-DEFAULT_FG_COLOR="black"
-XTERM_COLORS_SIZE=${#XTERM_COLORS[@]}
+readonly DEFAULT_FG_COLOR="black"
+readonly XTERM_COLORS_SIZE=${#XTERM_COLORS[@]}
 
-terms_number=1
-if [ $# -ge 1 ]; then
-    if [[ $1 =~ ^[0-9]+$ ]]; then
-        terms_number=$1
-    else 
-        echo "Usage: color_xterm [number]"
-        exit 1
+function main() {
+    local terms_number=1
+    if [ $# -ge 1 ]; then
+        # Check if param is an integer
+        if [[ $1 =~ ^[0-9]+$ ]]; then
+            local terms_number=$1
+        else 
+            echo "Usage: color_xterm [number]"
+            exit 1
+        fi
     fi
-fi
 
 
-counter=0
+    local counter=0
+    while [ $counter -lt $terms_number ]; do
+        local selected_color=${XTERM_COLORS[$((RANDOM%XTERM_COLORS_SIZE))]}
+        xterm -bg "$selected_color" -fg "$DEFAULT_FG_COLOR" &
+        local counter=$[counter + 1]
+    done
+}
 
-while [ $counter -lt $terms_number ]; do
-    selected_color=${XTERM_COLORS[$((RANDOM%XTERM_COLORS_SIZE))]}
-    xterm -bg $selected_color -fg $DEFAULT_FG_COLOR &
-    counter=$[counter + 1]
-done
+main "$@"
 
 # ===============================================
 #  END: C O L O R  X T E R M                    =
